### ISSUE TITLE
最佳实践：在Sidecar初始化完成后再启动应用容器

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-framework/istio-operation-bible#7]
https://imroc.cc/post/202105/sidecar-startup-order/

deployment 级别修改：
```yaml
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```

全局修改
```yaml
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  meshNetworks: 'networks: {}'
kind: ConfigMap
```
